server:
  port: 8000
#  servlet:
#    context-path: /mxd
#    tomcat:
#      uri-encoding: UTF-8
spring:
#  mvc:
#    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.188.102:3306/test?setUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# 开启mybatis与mybatis-plus 共用
mybatis-plus:
  type-aliases-package: com.hdu.mxd.entity
  mapper-locations: classpath:mappers/*Mapper.xml
  config-location: classpath:mappers/mybatisConfig.xml

mybatis:
  #MyBatis相关自定义配置
  # configLocation: classpath:mybatis.xml
  #实体类所做包
  type-aliases-package: com.hdu.mxd.entity
  #mapper.xml所在位置
  config-location: classpath:mappers/mybatisConfig.xml
  mapper-locations: classpath:mappers/*Mapper.xml

#mybatis-plus:
#  #MyBatis相关自定义配置
#  # configLocation: classpath:mybatis.xml
#  configuration:
#    config-location: classpath:mappers/mybatisConfig.xml
#    #mapper.xml所在位置
#    mapper-locations: classpath:mappers/*Mapper.xml
#  #实体类所做包
#  type-aliases-package: com.hdu.mxd.entity





#showSql
logging:
  level:
    com.hdu.mxd.mapper : debug


